services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=mahender
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=mahenderg.reddy@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=changeit
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db-data:
    driver: local
  pgadmin_data:
    driver: local
